### CONST FOR CONFLUENCE ###

URL = "http://localhost:8090"
USER = "sysadmin"
PASSWD = "phoenix"

PATH_WHB = "data/WHB"
PATH_WSS = "data/WSS"

SPACE_ID = 65591
SPACE_KEY = "PRED"
PARENT_ID_WHB = 1114148
PARENT_ID_WSS = 917507
